# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenappsanjay

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenappsanjay.azurecr.io/
        username: chickenappsanjay
        password: KYovQMjiQfkKLHS9Pic286vT1kyIfycbW2ijF2dE3T+ACRBxVM3J

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenappsanjay.azurecr.io/chicken:a50a30fbc53faea7ce592060d9a6ad55f86a4283
        file: ./Dockerfile
        load: false
        no-cache: false
        pull: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenappsanjay'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc7f25129a214516999e2f1cb58abd30 }}
        images: 'chickenappsanjay.azurecr.io/chickenappsanjay/chicken:${{ github.sha }}'